name: topicmodeling
channels:
  - defaults
  - conda-forge
dependencies:
  - gensim
  - matplotlib
  - notebook
  - numpy
  - pandas
  - python=3.8.5
  - python-dateutil
  - qgrid
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - stop-words
  - tqdm
